blog/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as v
from . import views

urlpatterns = [
    # url(r'^$', views.home_page, name='home'),
    path('', views.home_page, name='home_page'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_registration, name='registration'),
    path('groups/', views.GroupsList.as_view(), name='group_list'),
    path('groups/new/', views.GroupCreate.as_view(), name='group_create'),
    path('groups/<int:group_id>/', views.GroupPage.as_view(), name='group_info'),
    path('groups/<int:group_id>/update/', views.GroupUpdate.as_view(),
         name='group_update'),
    path('groups/<int:group_id>/delete/', views.GroupDelete.as_view(),
         name='group_delete'),
    path('groups/<int:group_id>/new_post/', views.PostCreate.as_view(),
         name='post_create'),
    path('posts/', views.PostsList.as_view(), name='post_list'),
    path('posts/<int:pk>', views.PostInfo.as_view(), name='post_info'),
    # path('posts/create/', views.PostCreate.as_view(), name='post_create'),
    path('posts/<int:post_id>/update/', views.PostUpdate.as_view(),
         name='post_update'),
    path('posts/<int:post_id>/delete/', views.PostDelete.as_view(),
         name='post_delete'),
    path('drafts/', views.DraftsList.as_view(), name='drafts_list'),
    path('posts/<int:draft_id>/publish/', views.publish, name='draft_publish'),
    path('groups/<int:group_id>/invite/', views.invite, name='invite')


]

project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Group(models.Model):

    THEME_CHOICES = (
        ('GE', 'General'),
        ('MU', 'Music'),
        ('SP', 'Sport'),
        ('TV', 'Television'),
        ('PL', 'Politics'),
        ('SP', 'Space'),
        ('HE', 'Health')
    )

    name = models.CharField(max_length=100)
    theme = models.CharField(choices=THEME_CHOICES, max_length=2)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='creator')
    date_created = models.DateTimeField(default=timezone.now)
    members = models.ManyToManyField(User, through='Membership', related_name='members')
    is_private = models.BooleanField(default=False)


    def __str__(self):
        return self.name

    @classmethod
    def create(cls, name, theme, creator):
        group = Group(name=name, theme=theme, creator=creator)
        group.save()
        return group


class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    date_joined = models.DateTimeField()

    @classmethod
    def create(cls, user, group):
        membership = Membership(user=user, group=group, date_joined=timezone.now)
        membership.save()
        return membership


    def __str__(self):
        return f"{self.user.username} in {self.group.name} group"


class Post(models.Model):

    title = models.CharField(max_length=100)
    text = models.TextField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_creator')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='post_group')
    date_created = models.DateTimeField(null=True)
    is_private = models.BooleanField(default=False)

    @classmethod
    def create(cls, title, text, creator, group):
        post = Post(title=title, text=text, creator=creator,
                    group=group)
        post.save()
        return post

blog/forms.py
from .models import Group, Post
from django import forms
from django.contrib.auth.models import User

class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = ['name', 'theme', 'creator']

    name = forms.CharField(label='name', max_length=100)
    theme = forms.ChoiceField(choices=Group.THEME_CHOICES)

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'text', 'creator', 'group']

    title = forms.CharField(label='title', max_length=100)
    text = forms.Textarea()

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (ListView, DetailView, View, TemplateView)
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.conf import settings
from .models import Group, Membership, Post
from .forms import GroupForm, PostForm
from django.utils import timezone
from django.template.response import TemplateResponse


import pdb


def home_page(request):
    return render(request, template_name='homepage.html')

def user_login(request):
    if request.method == "GET":
        return render(request, template_name='login.html')
    elif request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
            if user.check_password(password):
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return render(request, 'login.html', {'error': settings.LOGIN_ERROR_MESSAGE}, status=401)
                # return HttpResponse(settings.LOGIN_ERROR_MESSAGE, status=401)
                # return TemplateResponse(request, 'login.html',
                #                     context={'error': settings.LOGIN_ERROR_MESSAGE},
                #                     status=400)
        except User.DoesNotExist:
            return HttpResponse(settings.LOGIN_ERROR_MESSAGE, status=401)

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

def user_registration(request):
    if request.method == "GET":
        return render(request, template_name='registration.html')
    elif request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        try:
            user = User.objects.get(username=username)
            return HttpResponse(settings.REGISTRATION_USER_EXISTS_ERROR_MESSAGE,
                                status=400)
        except User.DoesNotExist:
            if password1 == password2:
                user = User.objects.create_user(username, email)
                user.set_password(password1)
                user.save()
                return HttpResponseRedirect('/')
            else:
                return HttpResponse(settings.REGISTRATION_PASSWORDS_ERROR_MESSAGE,
                                    status=400)


class GroupsList(LoginRequiredMixin, ListView):

    model = Group
    template_name = 'groups/groups_list.html'


class GroupPage(LoginRequiredMixin, TemplateView):

    def get(self, request, group_id):
        template_name = 'groups/group_info.html'
        group = get_object_or_404(Group, pk=group_id)
        post_list = Post.objects.filter(group=group_id).values()
        posts = [elem for elem in post_list]
        user = request.user
        is_member = self.is_member(user, group)
        is_creator = self.is_creator(user.pk, group_id)
        return render(request, template_name, {'is_member': is_member,
                                               'is_creator': is_creator,
                                               'group': group,
                                               'posts': posts})

    def post(self, request, group_id):
        group = get_object_or_404(Group, pk=group_id)
        user = request.user
        is_member = self.is_member(user, group)
        if is_member:
            membership = Membership.objects.get(group=group, user=user)
            membership.delete()
        else:
            Membership.objects.create(group=group, user=user,
                                      date_joined=timezone.now())
        return HttpResponseRedirect(f'/groups/{group_id}/')


    @staticmethod
    def is_member(user, group):
        try:
            Membership.objects.get(group=group, user=user)
            is_member = True
        except Membership.DoesNotExist:
            is_member = False
        return is_member

    @staticmethod
    def is_creator(user_id, group_id):
        user = User.objects.get(pk=user_id)
        group = Group.objects.get(pk=group_id)
        creator = group.creator
        if creator.pk == user.pk:
            return True
        return False


class GroupCreate(LoginRequiredMixin, TemplateView):

    def get(self, request):
        template_name = "groups/group_create.html"
        form = GroupForm()
        return render(request, template_name, {'form': form})

    def post(self, request):

        name = request.POST.get('name')
        theme = request.POST.get('theme')
        is_private = request.POST.get('private')

        creator = request.user
        data = {'name': name,
                'theme': theme,
                'creator': creator.pk}
        form = GroupForm(data)
        if form.is_valid():
            group = form.instance
            if is_private is None:
                group.save()
            else:
                group.is_private = True
                group.save()
                membership = Membership(user=creator, group=group, date_joined=timezone.now())
                membership.save()
            return HttpResponseRedirect('/groups/')
        return HttpResponse("Data is not valid", status=400)


class GroupUpdate(LoginRequiredMixin, TemplateView):

    def get(self, request, group_id):
        group = Group.objects.get(pk=group_id)
        form = GroupForm(instance=group)
        user = request.user
        template_name = "groups/group_form.html"
        if GroupPage.is_creator(user.pk, group_id):
            return render(request, template_name, {'form': form})
        return render(request, template_name, {'form': form,
                                            'error': "Only creator is allowed to update the group"})

    def post(self, request, group_id):
        user = request.user
        group = get_object_or_404(Group, id=group_id)
        if GroupPage.is_creator(user.pk, group_id):
            name = request.POST.get('name')
            theme = request.POST.get('theme')
            data = {'name': name, 'theme': theme, 'creator': group.creator.pk}
            form = GroupForm(data=data, instance=group)
            if form.is_valid():
                form.save()
                # return render(request, "groups/group_info.html")
                return HttpResponseRedirect(f'/groups/{group_id}/')
        return render(request,  "groups/group_form.html", {'error': "Only creator is allowed to update the group"})


class GroupDelete(LoginRequiredMixin, TemplateView):
    template_name = 'groups/group_form.html'

    def post(self, request, group_id):
        group = get_object_or_404(Group, pk=group_id)
        try:
            group.delete()
            return HttpResponseRedirect('/groups/')
        except:
            return HttpResponse("Couldn't delete", status=400)


@login_required
def invite(request, group_id):
    if request.method == "POST":
        user_current = request.user
        username = request.POST.get('invited_user')
        group = get_object_or_404(Group, pk=group_id)
        is_creator = GroupPage.is_creator(user_current.pk, group.pk)
        data = {'group': group,
                'is_member': True,
                'is_creator': is_creator}
        try:
            user = User.objects.get(username=username)
            try:
                member = Membership.objects.get(user=user, group=group)
                return render(request, 'groups/group_info.html',
                              {**data,'message': "User is a member already"})
            except Membership.DoesNotExist:
                membership = Membership(user=user, group=group, date_joined=timezone.now())
                membership.save()
            return render(request, 'groups/group_info.html', {**data,'message': "User was invited"} )

        except User.DoesNotExist:
            return render(request, 'groups/group_info.html', {**data, 'message': "User doesn't exist",})



# class PostPage(LoginRequiredMixin, TemplateView):
#
#     def get(self, request, **args):
#         template_name = 'posts/posts_list.html'
#
#

class PostsList(LoginRequiredMixin, ListView):

    model = Post
    template_name = 'posts/posts_list.html'

class PostInfo(LoginRequiredMixin, DetailView):

    model = Post
    template_name = 'posts/post_info.html'

class PostCreate(LoginRequiredMixin, TemplateView):

    def get(self, request, group_id):
        template_name = 'posts/post_create.html'
        form = PostForm()
        creator = request.user
        group = get_object_or_404(Group, pk=group_id)
        if GroupPage.is_member(creator, group):
            return render(request, template_name, {'form': form})
        return render(request, 'posts/post_create.html',
                      {'error': "You must join group to create posts"})

    def post(self, request, group_id):
        title = request.POST.get('title')
        text = request.POST.get('text')
        creator = request.user
        publish = request.POST.get('publish')
        group = get_object_or_404(Group, pk=group_id)
        if GroupPage.is_member(creator, group):
            data = {'title': title,
                    'text': text,
                    'creator': creator.pk,
                    'group': group.pk}
            form = PostForm(data)
            if form.is_valid():
                post = form.instance
                if publish is None:
                    post.date_created = timezone.now()
                post.save()
                if group.is_private == True:
                    post.is_private = True

blog/templates/groups/group_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h2 class="header-center">Create new group</h2>
    <div class="col-9">
    <form style="margin-left: 30%"  method="post">
    {% csrf_token %}
  <div class="form-group">
    {{ form.name|as_crispy_field }}
  </div>
  <div class="form-group">
    {{ form.theme|as_crispy_field }}
  </div>

  <div>
      <input class="form-check-input" type="checkbox" name="private"> Make private

  </div>

  <button type="submit" class="btn btn-success">Save</button>
</form>
    </div>


{#    TODO: try to connect crispy or use another way to add bootstrap to django forms #}

{% endblock %}

blog/templates/groups/group_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if error %}
    <h2>{{ error }}</h2>
    {% else %}
    <h2 class="header-center">Update {{ form.name.value }}</h2>
{#TODO: add bootstrap to django forms#}
    <form style="margin-left: 40%"  method="post">
    {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Name</label>
    {{ form.name|as_crispy_field }}
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Theme</label>
    {{ form.theme|as_crispy_field }}
  </div>

  <button type="submit" class="btn btn-success">Save</button>
</form>
    {% endif %}

{% endblock %}

blog/templates/groups/group_info.html
{% extends 'base.html' %}

{% block content %}

    <h2 class="header-center">{{ group.name }}</h2>


    <div class="card" style="width: 25rem; margin-left: 40%">
  <div class="card-body">
    <h5 class="card-title">Welcome to {{ group.name }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">Created: {{ group.date_created }} by {{ group.creator.username }}</h6>
    <h6 class="card-subtitle mb-2 text-muted">Topic: {{ group.get_theme_display }}</h6>
    <h6 class="card-subtitle mb-2 text-muted">Members:  {{ group.members.count }}</h6>

      {% if is_member %}
          {% if is_creator %}

 <a class="btn btn-success" href="{% url 'group_update' group.pk %}" role="button">Update</a>
      <form method="post" action="{% url 'group_delete' group.pk %}"> {% csrf_token %}
    <button class="btn btn-danger"  type="submit">Delete</button>
          </form>
              {% endif %}
      <form method="post">
              {% csrf_token %}
              <button class="btn btn-danger" type="submit" >Leave</button>
          </form>
      {% elif not group.is_private %}

          <form method="post">
              {% csrf_token %}
              <button class="btn btn-warning" type="submit" >Join</button>
          </form>

      {% endif %}

  {% if group.is_private and is_member %}
      <br>
      <form method="post" action="{% url 'invite' group.pk %}">
          {% csrf_token %}
  <div class="input-group flex-nowrap">
  <div class="input-group-prepend">
    <span class="input-group-text" id="addon-wrapping">@</span>
  </div>

  <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping" name="invited_user">
   <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Invite</button>
</div></form>
      {% if message %}
          <h5> {{ message }}</h5>
          {% endif %}
  {% endif %}


  </div>
    {% if group.is_private and is_member or not group.is_private %}
</div>
        <h2 class="header-center">Posts in the group:</h2>

    <a class="btn btn-success" href="{% url 'post_create' group.pk %}" role="button">Create new</a>
    {% for post in posts %}
    <div class="card ml-4" style="width: 50rem; ">
  <div class="card-header">
    {{ post.date_created }}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <p class="card-text">{{ post.text }}</p>
    <a href="{% url 'post_info' pk=post.id %}" class="btn btn-primary">Detail</a>
  </div>
</div>
    {% endfor %}
    {% endif %}

{% endblock %}

blog/templates/groups/groups_list.html
{% extends 'base.html' %}
{% block content %}
<div class="header">
<h2 class="header-center">Groups:</h2>
</div>
    <div class="ml-5">
    <a class="btn btn-success" href="{% url 'group_create' %}" role="button">Create new</a>
    </div>
    <div class="container">
    <div class="row">
    <div class="col-8">
    {% for group in group_list %}

        <div class="card" style="width: 25rem; ">
  <div class="card-body">
    <h5 class="card-title"><a class="nav nav-elem" href="{% url 'group_info' group_id=group.pk %}">
            {{ group.name }}</a>  {% if group.is_private %}<span class="badge badge-secondary">private</span></h5> {% endif %}

    <h6 class="card-subtitle mb-2 text-muted">Created: {{ group.date_created }} by {{ group.creator.username }}</h6>
    <h6 class="card-subtitle mb-2 text-muted">Theme: {{ group.get_theme_display }}</h6>
    <h6 class="card-subtitle mb-2 text-muted">Members:  {{ group.members.count }}</h6>



  </div>
    {% endfor %}
    </div>
    </div>

    </div>
    </div>

{% endblock %}